name: test-my-app

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]
# we have some extra configurations on github repository settings in order to block merge when the action fails
# see settings / rules

jobs:
  test:
    name: Integration Tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: futureware-tech/simulator-action@v3
        with:
          model: 'iPhone 15'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter test integration_test/app_test.dart
# You can use flavors to run test, e.g. flutter test integration_test --dart-define=envFlavor=dev --flavor dev
# Alternatively, if you're using a custom script to run tests, you can use:
# - run: ./path/to/your/script.sh